#!/bin/sh

THRESHOLD=20
CACHE_SIZE=8
RANDOM_RULES_NUM=2
RUN_TIME=600
PORT=50105
EVICTION_THRESHOLD=6
READ_COUNTER_INTERVAL=1
TIME_BETWEEN_RUNS=5

./build.sh $THRESHOLD $CACHE_SIZE $RANDOM_RULES_NUM $RUN_TIME $PORT $EVICTION_THRESHOLD $READ_COUNTER_INTERVAL

